// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcnmzrrpagsyuxczueyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjbm16cnJwYWdzeXV4Y3p1ZXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzQ2MjEsImV4cCI6MjA2MjExMDYyMX0.NRvGV7bUAluxep49ObE6hhPObdGqLxpm6yQNqEh6ELE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);